name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  pr-number:  # id of input
    description: 'Pull Request ID Number'
    required: false
  artifact-name:
    description: 'Artifact Name to Pass Through'
    required: false
outputs:
  artifact-name: # id of output
    description: The artifact name
runs:
  using: 'node20'
  main: 'dist/index.js'
