name: Branch Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analize:
    if: (github.event.label.name == vars.OUTDATED_BRANCH_TRIGGER_LABEL) || !github.event.label.name
    name: Test & Analize
    uses: ./.github/workflows/test-and-scan.yaml
    secrets: inherit

  Compile:
    if: (github.event.label.name == vars.OUTDATED_BRANCH_TRIGGER_LABEL) || !github.event.label.name
    name: Compile Test
    uses: ./.github/workflows/compile-test.yaml
    secrets: inherit
  