name: Branch Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      checkout-ref:
        required: false
        type: string

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analize:
    name: Test & Analize
    uses: ./.github/workflows/test-and-scan.yaml
    secrets: inherit
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
  Compile:
    name: Compile Test
    uses: ./.github/workflows/compile-test.yaml
    secrets: inherit
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
  