name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  ARTIFACT_NAME: ${{ inputs.artifact-name || github.event.pull_request.number || 'main'}}

jobs:
  Docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:app-${{ env.ARTIFACT_NAME }}