name: Rebuild PR

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: false
        type: string
      pr-number:
        required: true
        type: number
      pr-context:
        required: true
        type: string

permissions:
  pull-requests: write

env:
  GITHUB_CONTEXT: ${{ toJSON(inputs.pr-context) }}

jobs:
  Build:
    name: Build
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
  BranchAnalysis:
    name: Test & Analize
    uses: ./.github/workflows/branch-analysis.yaml
    secrets: inherit
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
  Unlabel:
    name: Remove label
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Remove label
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let fs = require('fs');
          let issue_number = ${{ env.PR_NUMBER }};
          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            name: '${{ vars.OUTDATED_BRANCH_TRIGGER_LABEL }}'
          });
