name: Update Open PRs

on:
  push:
    branches: [ "main" ]

permissions:
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: list all open pull requests
      id: list
      uses: GitHub-Actions-Demo/action-pr-update/@v0.0.1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: output
      run: echo '${{ steps.list.outputs.open-pr-list }}'