name: Update Open PRs

on:
  push:
    branches: [ "main" ]

permissions:
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: list all open pull requests
      id: list
      uses: andrea-armstrong/github-list-pull-requests@v1.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        state: 'open'
    - name: output
      run: echo '${{ steps.list.outputs.pullRequestNumbers }}'