name: Update Open PRs

on:
  push:
    branches: [ "main" ]

permissions:
  pull-requests: write
  actions: write
  contents: read
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app_id: ${{ secrets.WORKFLOW_DISPATCH_TOKEN_ID }}
        private_key: ${{ secrets.WORKFLOW_DISPATCH_TOKEN_PRIVATE_KEY }}

    - name: Rebuild all open pull requests
      id: workflows
      env:
        GITHUB_TOKEN:  ${{ steps.generate_token.outputs.token }}
      uses: GitHub-Actions-Demo/action-pr-update/@v0.0.14
      with:
        token: ${{ steps.generate_token.outputs.token }}
        label: ${{ vars.OUTDATED_BRANCH_TRIGGER_LABEL }}
        workflow_id: rebuild-pull-request.yaml