name: Update Open PRs

on:
  push:
    branches: [ "main" ]

permissions:
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Label all open pull requests
      id: list
      uses: GitHub-Actions-Demo/action-pr-update/@v0.0.4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: ${{ vars.OUTDATED_BRANCH_TRIGGER_LABEL }}