name: Update Open PRs

on:
  push:
    branches: [ "main" ]

permissions:
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Rebuild all open pull requests
      id: list
      uses: GitHub-Actions-Demo/action-pr-update/@v0.0.7
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: ${{ vars.OUTDATED_BRANCH_TRIGGER_LABEL }}
        workflow_id: ./.github/workflows/rebuild-pull-request.yaml